services:
  web:
    build: .
    container_name: bic-experinece
    ports:
      - "8085:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
